### ISSUE TITLE
Not compatible with setuptools v72

### ISSUE THREAD

**Issue by fedepad** [chaimleib/intervaltree#138]
Hi, thanks for this package.
I was just hit by: https://github.com/pypa/setuptools/issues/4519 and it looks setuptools v72 doesn't have `setuptools.command.test` anymore.
This package is affected by it.
Here the stacktrace:
```bash
8.047   Downloading intervaltree-3.1.0.tar.gz (32 kB)
8.076   Preparing metadata (setup.py): started
8.288   Preparing metadata (setup.py): finished with status 'error'
8.294   error: subprocess-exited-with-error
8.294
8.294   × python setup.py egg_info did not run successfully.
8.294   │ exit code: 1
8.294   ╰─> [6 lines of output]
8.294       Traceback (most recent call last):
8.294         File "<string>", line 2, in <module>
8.294         File "<pip-setuptools-caller>", line 34, in <module>
8.294         File "/tmp/pip-install-qnq42f2u/intervaltree_199a4c9e333343e6955868e022c9580e/setup.py", line 32, in <module>
8.294           from setuptools.command.test import test as TestCommand
8.294       ModuleNotFoundError: No module named 'setuptools.command.test'
8.294       [end of output]
8.294
8.294   note: This error originates from a subprocess, and is likely not a problem with pip.
8.329 error: metadata-generation-failed
8.329
8.329 × Encountered error while generating package metadata.
8.329 ╰─> See above for output.
8.329
8.329 note: This is an issue with the package mentioned above, not pip.
8.329 hint: See above for details.
```

Best!

**Comment by nazimisik** [comment]
setuptools newest version also helps, no need to wait for the new release now

**Comment by jo-bitsch** [comment]
while the newest version of setuptools (`v72.1.0`) reinstates the test command, it is still [deprecated](https://setuptools.pypa.io/en/stable/history.html#v72-1-0). So a new release might not be as urgent for now as it may have seemed yesterday. However, a new version is still needed at some point.
