### ISSUE TITLE
symmetric_difference_update and intersection_update raise a RuntimeError

### ISSUE THREAD

**Issue by ProgVal** [chaimleib/intervaltree#37]
Hi,

`symmetric_difference_update` updates the current tree while iterating on it, which raises a RuntimeError.

``` python
$ PYTHONHASHSEED=0 python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from intervaltree import IntervalTree, Interval
>>> t1 = IntervalTree({Interval(1, 2), Interval(2, 3), Interval(3, 4)})
>>> t2 = IntervalTree({Interval(3, 4)})
>>> t1.symmetric_difference_update(t2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/progval/.local/lib/python3.4/site-packages/intervaltree/intervaltree.py", line 456, in symmetric_difference_update
    for iv in self:
RuntimeError: Set changed size during iteration
```

Note that this error will not happen if the only modification happens on the last iteration.

Version: 2.1.0, from PyPI.

**Comment by ProgVal** [comment]
Same issue with `intersection_update`.

**Comment by chaimleib** [comment]
Fixed in with the v3 release!
