### ISSUE TITLE
KeyError on removal

### ISSUE THREAD

**Issue by alexreg** [chaimleib/intervaltree#85]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/intervaltree/node.py", line 248, in remove_interval_helper
    self.s_center.remove(interval)
KeyError: Interval(64993436, 76836782, ...)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/bin/dna-kit", line 290, in <module>
    main()
  File "/Users/alex/bin/dna-kit", line 287, in main
    args.subcommand(args, service=service, relatives=relatives, fatal_error=parser.error)
  File "/Users/alex/bin/dna-kit", line 172, in find_groups_command                                      interval_tree.remove(cur_overlap)
  File "/usr/local/lib/python3.7/site-packages/intervaltree/intervaltree.py", line 367, in remove
    self.top_node = self.top_node.remove(interval)
  File "/usr/local/lib/python3.7/site-packages/intervaltree/node.py", line 214, in remove
    return self.remove_interval_helper(interval, done, should_raise_error=True)
  File "/usr/local/lib/python3.7/site-packages/intervaltree/node.py", line 251, in remove_interval_helper
    raise KeyError(interval)
KeyError: Interval(64993436, 76836782, ...)
```

**Comment by chaimleib** [comment]
Hello! Could you post which version of intervaltree you had this bug with?

**Comment by alexreg** [comment]
@chaimleib 3.0.2

**Comment by chaimleib** [comment]
Thanks!
If an interval is not present in the tree, and `remove()` is called on it, this error is expected to occur. If you would like to silently continue instead, you could call `discard()` on your interval instead. Does this help in your use case?

**Comment by alexreg** [comment]
@chaimleib Ah, it seems you're right. I thought my code had guaranteed I would only ever be removing an element that already exists in the interval tree, but it seems that assumption is incorrect in some cases. Thank you.

**Comment by chaimleib** [comment]
I don't think duplicate intervals should be an issue, as long as they don't compare equal. If an interval already exists in the tree, adding it a second time will silently do nothing. If you really want to add two intervals with the same range, you can differentiate them by giving them different `data` fields.
It looks to me like the error is actually happening at the remove step, which you can confirm with the files and line numbers in the stack trace.
```
  File "/Users/alex/bin/dna-kit", line 172, in find_groups_command                                      interval_tree.remove(cur_overlap)
  File "/usr/local/lib/python3.7/site-packages/intervaltree/intervaltree.py", line 367, in remove
    self.top_node = self.top_node.remove(interval)
```

**Comment by alexreg** [comment]
Weird that it should happen then... maybe a bug after all. Because I'm literally removing intervals returned by `overlap`, in a loop, and no others.
